# sortmedia
:toc:
:toclevels: 5

This linux desktop app sorts media to folders in Year/Month structure.
It skips files that are already in destination folder. 
It uses "analyzors" to get the relevant date from a media file. Currently, there are two analyzors:

* an EXIF-Analyzor, which gets the EXIF shottime, and
* an RegExp-Analyzor, which currently is hardcoded to a YYYYMMDD_HHmmSS pattern.

If the analyzors failed to get a relevant date for a file, such file is copied to a folder for unclassified files.

[WARNING]
I've created sortmedia for my personal use only. Perhaps, it is also useful for others. However, I take **no responsibility** for damages whatsoever.

## Usage

For development run
```bash
  flutter run
```  

To build
```bash
  flutter build linux
```  

Before building or running, you have to generate serialization classes by
```bash
   dart run build_runner build
```

After build and packaging (see <<Deployment for Debian, below>>), on Debian/Ubuntu/Linux Mint, you can install the `.deb`-package in
`dist/${VERSION}/sortmedia-${VERSION}-linux.deb`.

## Development

### Architecture

#### Organization of Features

lib/src/features contain subfolders

* ui
* uistate - state that contains code related to widgets
  - no import of a ui dart file
* state - pure state 
  - no import of a flutter package 
  - no import of a ui or uistate dart file
* data or engine - logic to calculate, fetch or combine data 
  - no import of ui/uistate/state dart file

### Checklist for Some Changes

#### Version Bump

For version bumps, you have to update

* link:pubspec.yaml[]
* link:lib/features/home/ui/sm_scaffold.dart[]

#### New Screen

* Create the new screen in `lib/features/*/ui/`
* Append it to `navDests` in link:lib/features/navigation/uistate/current_screen_model.dart[] 
* Append the routes in link:lib/main.dart[]

#### New Analyzor

* Create new Analyzor in link:lib/features/analyze/engine[]
* Add new Analyzor to list in link:lib/features/analyze/uistate/analyzor_list.dart[]
* If necessary, create new AnalyzorConfigWidget in link:lib/features/config/ui[]
* If necessary, add new AnalyzorConfigWidget to link:lib/features/config/ui/analyzor_config_widget_factory.dart[]
* Make it known to dart_mappable using `NewAnalyzorMapper.ensureInitialized()` in link:lib/main.dart[]

### Deployment for Debian

To create the .deb file, you have to know the dependencies. It helps to run 

```bash
  flutter build
  objdump -p build/linux/x64/release/bundle/sortmedia \
    | grep NEEDED  | cut --delim  ' ' --fields 18 \
    | xargs -n1 dpkg -S | grep -v :i386: | grep -v libflutter_linux_gtk.so
```

It shows the required packages. Those package have to inserted into 
the `dependencies:` section of link:linux/packaging/deb/make_config.yaml[].

The required tool fastforge has to be installed:

```bash
  dart pub global activate fastforge
```

Run it but check correct umask:
```bash
umask 0002
fastforge package --platform linux --targets deb
```


## ToDo

* Refactor: Base log- and home screen on SmScaffold
* continue translation to english 
* Refactor: navDests in link:lib/features/navigation/uistate/current_screen_model.dart[] should also provide the Routes required in link:lib/main.dart[]
* Bug: Analysis data is not shown because
* Make it deployable as a .deb package
** uninstall bug: why does aptitude complain about non-empty /opt folder?
* screenshot in README
* user docs 
** create special folder docs
** link to github user docs file from app
* move to separate material_ui package
** first check in a simple project, if l10n works with new package (did not with flutter 3.47.2)
** then: `dart fix --apply --code=migrate_design_widgets`
* Bug: when scrolling on config screen, analyzors views should not scroll
  into the introductory text. 
* show processed files with filters
* allow multiple source-dest-pairs, which can be separetely activated
* clean logs
** scan progress
** whole copy progress and 
** copy progress of single file
* optionally use file changed time
* create extra tab for extended logs
* On main page, make size of logs settable
* create button to show directories in system folder explorer
* allow to create regex filename parser
* choose not classified directory (default: "others" in destination root directory)
* choose if files are copied, moved or linked
* abort button
* parallelize list files, parse file, copy files tasks
* provide white list of files to be analyzed or a black list or both
